config/routes.rb
Rails.application.routes.draw do

  # Pagina Principal
  get 'home', to: 'welcome#index'
  # Cerrar session
  get 'logout', to: 'sessions#destroy'

  get 'register', to: 'users#new'

  resources :meters

  resources :users

  resources :sessions

  root 'sessions#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meter.rb
class Meter < ApplicationRecord
    has_many :cost_by_resources , :dependent => :delete_all
    has_many :activity_by_products, through: :cost_by_resources
    has_many :resources, through: :cost_by_resources
    has_many :subresources, through: :cost_by_resources
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create
  before_save :encrypt_password
  after_save :clear_password
  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
    end
  end
  def clear_password
    self.password = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :require_online
  protect_from_forgery with: :exception
  $session = nil
  private
  def role_template

  end
  def require_online
    if cookies[:key].nil?
      if self.controller_name != "sessions" || self.controller_name != "users"
        redirect_to root_path
      else
      end
    else
      @session =  Session.find(cookies[:key])
      if @session.nil?
        redirect_to root_path
      else
      end
    end
  end
end

app/controllers/meters_controller.rb
class MetersController < ApplicationController
	def index
        @meters = Meter.all
    end
    def show
        @meter = Meter.find(params[:id])
    end
    def new
        @meter = Meter.new
    end
    def edit
        @meter = Meter.find(params[:id])
    end
    def create
        @meter = Meter.new(meter_params)
        if @meter.save
            redirect_to meters_path
        else
            render 'new'
        end
    end
    def update
        @meter = Meter.find(params[:id])

        if @meter.update(meter_params)
        redirect_to meters_path
        else
        render 'edit'
        end
    end
    def destroy
      @meter = Meter.find(params[:id])
      @meter.destroy

        redirect_to meters_path
    end
    private
    def meter_params
        params.require(:meter).permit(:unity,:type_unity)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = Session.new
    render layout: false
  end
  def create
    @time_init = DateTime.now
    @time_end = @time_init + 30.minutes
    @user = params[:session][:user]
    @password = params[:session][:password]
    @user_exist = User.find_by(username: @user)
    @session = Session.new(:user_id => @user_exist.id, :time_init => @time_init, :time_end => @time_end )
    @session.save
    if @user_exist
      @encrypted = @user_exist.encrypted_password
      @salt = @user_exist.salt
      @validate_password = BCrypt::Engine.hash_secret(@password, @salt)
      if @validate_password == @encrypted
        @session_act = @session.id
        cookies.delete :key
        cookies[:key] = @session_act
        redirect_to home_path
      else
        render json: 'clave erronea'
        # Clave Erronea
      end
    else
      render json: 'El usuario no existe'
      # Usuario no existe
    end
  end
  def destroy
    cookies.delete :key
    $session = nil
    redirect_to root_path

  end

  private
  def session_params
    params.require(:session).permit(:user,:time_init => @time_init,:time_end => @time_end)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render layout: false
  end
  def create
    @user = User.new(users_params)
    if @user.save
      redirect_to root_path
    else
      render "new"
    end
  end
  private
  def users_params
    params.require(:user).permit(:username,:email,:password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
=begin
    puts case $user.role_id
           when 1

           when 2

           else
             render json: 'acceso denegado'
         end
=end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meters_helper.rb
module MetersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= favicon_link_tag 'icon.ico' %>
  <title>RUSS</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>

</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="header col-xs-12" style="background-image: url(<%= image_url("header.svg") %>)">
      <div class="row">
        <div class="col-xs-4 col-md-3 text-center name_app">
          <div id="button_menu" onclick="OpenCloseMenu()"><span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></div>
          <div> <%= image_tag "logo_2.png" , class: "logo2" %> </div>
        </div>
        <div class="col-xs-4 col-md-6 text-center name_app">
          <a href="/home">
            <%= image_tag "logo.png" , class: "logo" %>
          </a>
        </div>
        <div class="col-xs-4 col-md-3 text-center">
          <div class="button_log_out text-right">
            <!--<%= link_to ('<i class="glyphicon glyphicon-user"></i>').html_safe %>-->
            <%= link_to ('<i class="glyphicon glyphicon-log-out"></i>').html_safe, 'logout', data: { confirm: 'Esta seguro?' } %>
            <!--<%= link_to ('<i class="glyphicon glyphicon-bell"></i>').html_safe %>-->
          </div>
        </div>
      </div>
    </div>
    <div class="space-header col-xs-12">
      <div class="row">
        <div class="col-md-2 text-center name_app">
          <h3>RUSS</h3>
        </div>
        <div class="col-md-2">
          <p></p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div id="sub_menu" class="col-md-2">
      <div class="row">
        <div class="menu col-md-11">
          <ul class="nav nav-pills nav-stacked">

            <li><%= link_to ('<i class="glyphicon glyphicon-hourglass"></i> <span>Medidas</span>').html_safe, controller: 'meters' %></li>

          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-2">
      <p></p>
    </div>
    <div class="col-md-8">
      <div class="content row">
        <div class="col-md-12">
          <div class="alert alert-success alertSuccess" role="alert" style="display: none;"></div>
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/application1.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>RUSS</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application1', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application1', 'data-turbolinks-track': 'reload' %>

</head>
<body>
<div id="wrapper">
  <div class="overlay"></div>

  <!-- Sidebar -->
  <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
    <ul class="nav sidebar-nav">
      <li class="sidebar-brand">
        <a href="#">
          Brand
        </a>
      </li>
      <li>
        <a href="#">Home</a>
      </li>
      <li>
        <a href="#">About</a>
      </li>
      <li>
        <a href="#">Events</a>
      </li>
      <li>
        <a href="#">Team</a>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Works <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li class="dropdown-header">Dropdown heading</li>
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li><a href="#">Separated link</a></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
      <li>
        <a href="#">Services</a>
      </li>
      <li>
        <a href="#">Contact</a>
      </li>
      <li>
        <a href="https://twitter.com/maridlcrmn">Follow me</a>
      </li>
    </ul>
  </nav>
  <!-- /#sidebar-wrapper -->

  <!-- Page Content -->
  <div id="page-content-wrapper">
    <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
      <span class="hamb-top"></span>
      <span class="hamb-middle"></span>
      <span class="hamb-bottom"></span>
    </button>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->
</body>
</html>

app/views/meters/_form.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <%= form_for @meter,:remote => true do |f| %>
          <div class="modal-body">
            <div class="alert alert-danger" role="alert" style="display: none;"></div>
            <div class="form-group">
              <%= f.text_field :unity, class: "form-control input-lg", placeholder: "Nombre De La Unidad" %>
            </div>
            <div class="form-group">
              <%= f.text_field :type_unity, class: "form-control input-lg", placeholder: "Nombre Del Tipo De Unidad" %>
            </div>
          </div>

          <div class="modal-footer">
            <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
          </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div>
</div>

app/views/meters/create.js.erb
<% if @meter.errors.empty? %>
$('#product-modal').modal('hide');
<% else %>
alert('<%= @meter.errors.full_messages[0] %>');
<% end %>

app/views/meters/edit.html.erb
      <h1>
        Medida
        <small>Editar</small>
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
        <div class="col-lg-12 col-xs-12">
            <%= render 'form' %>
            <%= link_to 'Back', generators_path %>
        </div>
      </div>

app/views/meters/edit.js.erb
$('<%= j render "form", title: "Modificar La Medida" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/meters/index.html.erb
<h1>
  Medidas
  <%= link_to ('<i class="glyphicon glyphicon-plus"></i>').html_safe, new_meter_path, remote: true,:class => "btn btn-primary button-white-new" %>
</h1>
<!-- Small boxes (Stat box) -->
<div class="row">
  <div class="col-xs-12">
    <table  class="table table-bordered text-center">
      <thead>
        <tr>
          <th>Unidad de Medida</th>
          <th>Tipo de Medida</th>
          <th>Opciones</th>
        </tr>
      </thead>
      <% @meters.each do |g| %>
        <tr>
          <td><%= g.unity %></td>
          <td><%= g.type_unity %></td>
          <td>
            <%= link_to ('<i class="glyphicon glyphicon-pencil"></i>').html_safe, edit_meter_path(g),remote: true %>
            <%= link_to ('<i class="glyphicon glyphicon-remove"></i>').html_safe, meter_path(g), method: :delete,data: { confirm: 'Esta seguro?' } %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/meters/new.html.erb
      <h1>
        Nueva Unidad de Negocio
        <small>Crear</small>
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
        <div class="col-lg-12 col-xs-12">
            <%= render 'form' %>
            <%= link_to 'Back', generators_path %>
        </div>
      </div>

app/views/meters/new.js.erb
$('<%= j render "form", title: "Nueva Medida" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/meters/show.html.erb
      <h1>
        Unidad de Negocio
        <small>Ver</small>
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
        <div class="col-lg-12 col-xs-12">
            <p>
                <strong>Unidad de medida</strong>
                <%= @meter.unity %>
            </p>
            <p>
                <strong>tipo de medida:</strong>
                <%= @meter.type_unity %>
            </p>
            
            <%= link_to 'Back', meters_path %>
        </div>
      </div>

app/views/meters/update.js.erb
<% if @meter.errors.empty? %>
$('#product-modal').modal('hide');
<% else %>
// show_1 first error
alert('<%= @meter.errors.full_messages[0] %>');
<% end %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= favicon_link_tag 'icon.ico' %>
  <title>RUSS</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>

</head>
<body>
<% @page_title = "UserAuth | Signup" %>
<div class="col-md-4 col-md-offset-4">
  <div class="content row">
    <div class="col-md-12 text-center">
      <div class="alert alert-success alertSuccess" role="alert" style="display: none;"></div>
      <div class="Sign_Form">
        <h1>Sign Up</h1>
        <%= form_for @user do |f| %>
            <p> Username:</br> <%= f.text_field :username%> </p>
            <p> Email:</br> <%= f.text_field :email%> </p>
            <p> Password:</br> <%= f.password_field :password%></p>
            <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
            <%= f.submit :Signup %>
        <% end %>
        <% if @user.errors.any? %>
            <ul class="Signup_Errors">
              <% for message_error in @user.errors.full_messages %>
                  <li>* <%= message_error %></li>
              <% end %>
            </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-xs-6 col-md-4 row_home">
    <%= link_to ('<div class="col-md-10 col-md-offset-1 block_home"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span><br>UNIDADES DE NEGOCIO</div>').html_safe, controller: 'business_units' %>
  </div>
  <div class="col-xs-6 col-md-4 row_home">
    <%= link_to ('<div class="col-md-10 col-md-offset-1 block_home"><span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></span><br>ORDENES DE PROCEDIMIENTO</div>').html_safe, controller: 'production_orders' %>
  </div>
  <div class="col-xs-6 col-md-4 row_home">
    <%= link_to ('<div class="col-md-10 col-md-offset-1 block_home"><span class="glyphicon glyphicon-compressed" aria-hidden="true"></span><br>UNIDADES DE GESTION</div>').html_safe, controller: 'management_units' %></li>
  </div>
  <div class="col-xs-6 col-md-4 row_home">
    <%= link_to ('<div class="col-md-10 col-md-offset-1 block_home"><span class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span><br>PRODUCTOS</div>').html_safe, controller: 'macroproducts' %>
  </div>
  <div class="col-xs-6 col-md-4 row_home">
    <%= link_to ('<div class="col-md-10 col-md-offset-1 block_home"><span class="glyphicon glyphicon-leaf" aria-hidden="true"></span><br>RECURSOS</div>').html_safe, controller: 'resources' %></li>
  </div>
  <div class="col-xs-6 col-md-4 row_home">
    <%= link_to ('<div class="col-md-10 col-md-offset-1 block_home"><span class="glyphicon glyphicon-hourglass" aria-hidden="true"></span><br>MEDIDAS</div>').html_safe, controller: 'meters' %>
  </div>
  <!--<div class="col-xs-6 col-md-4 row_home">
    <%= link_to ('<div class="col-md-10 col-md-offset-1 block_home"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span><br>Gestion De Materiales</div>').html_safe, kardexes_path %>
  </div>
  <div class="col-xs-6 col-md-4 row_home">
    <div class="col-md-10 col-md-offset-1 block_home">
      <span class="glyphicon glyphicon-stats" aria-hidden="true"></span><br>
      Reportes
    </div>
  </div>
  <div class="col-xs-6 col-md-4 row_home">
    <%= link_to ('<div class="col-md-10 col-md-offset-1 block_home"><span class="glyphicon glyphicon-resize-small" aria-hidden="true"></span><br>Actividades De Apoyo</div>').html_safe, indirect_activities_path %>
  </div>-->
  <div class="col-xs-6 col-md-4 row_home">
    <%= link_to ('<div class="col-md-10 col-md-offset-1 block_home"><span class="glyphicon glyphicon-magnet" aria-hidden="true"></span><br>ENLACE ACTIVIDADES DE APOYO</div>').html_safe, new_indirect_activity_by_product_path %>
  </div>
</div>